In [1]:
import numpy as np

# Vector Operations

In [15]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [16]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

# Multiplication

In [18]:
def vect_vect_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [19]:
vect_vect_multiply(u,v)

14.0

In [20]:
u.dot(v)

14

In [21]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])


In [22]:
def matrix_vect_multiply(u,v):
    assert u.shape[1] == v.shape[0]

    num_rows = u.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vect_vect_multiply(u[i], v)
    
    return result


In [23]:
matrix_vect_multiply(U, v)

array([14.,  5.,  5.])

In [24]:
U.dot(v)

array([14,  5,  5])

In [25]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [26]:
def matrix_matrix_multiply(U,V):
    assert U.shape[1] == V.shape[0]

    result = np.zeros((U.shape[0], V.shape[1]))

    for i in range(V.shape[1]):
        vi = V[:, i]
        Uvi = matrix_vect_multiply(U, vi)
        result[:, i] = Uvi
    return result

In [27]:
matrix_matrix_multiply(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [28]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [33]:
I = np.eye(3)

In [34]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Matrix Inverse

In [36]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [38]:
Vs_inv = np.linalg.inv(Vs)

In [39]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])