In [1]:
import numpy as np

# Creating Arrays

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.4)

array([2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4, 2.4])

In [6]:
a = np.array([1,2,3,5,7,12])
a[2]

3

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-Dimensional Arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [15]:
n[0][1] = 20

In [16]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
n[2] = [1,1,1]

In [19]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [23]:
n[:,2] = [0,1,2]

In [24]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly Generated Arrays

In [29]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [28]:
np.random.randn(5,2)

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [30]:
np.random.randint(low=0, high=100, size=(5,2))

array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]])

# Element-wise operations

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a + 1

array([1, 2, 3, 4, 5])

In [37]:
b = (10 + (a *2)) ** 2 / 100

In [38]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison Operations

In [39]:
a  >=  2

array([False, False,  True,  True,  True])

In [40]:
a > b

array([False, False,  True,  True,  True])

In [41]:
a[a> b]

array([2, 3, 4])

# Summarizing Operations

In [42]:
a.min()

0

In [43]:
a.max()

4

In [44]:
a.mean()

2.0

In [45]:
a.sum()

10

In [46]:
a.std()

1.4142135623730951